# The file contains the properties for py.chaos

runner:
    # generic py.chaos settings
    network: minicloud_default
    log_level: info
    error_threshold: 1
    trigger: 30s
  
  # let chaos run
chaos:
  # Chaos events
    stop:
      enabled: true
    reboot:
      enabled: true
    terminate:
      enabled: true
    burncpu:
      enabled: true
    burnram:
      enabled: true
  # burnio:
      #enabled: false
  # burndisk:
      # enabled: false
    killprocesses:
      enabled: false
  
  
# specifiy instances to run each chaos against, if not mentioned here
# all enabled chaos actions would be enabled for all running instances
instances:
   reboot: [redis, cstar]
   terminate: apigateway
   burncpu: [relay, auth]
   killprocesses: machinebus
  
# Individual chaos event specific options , otherwise default values persists
burncpu:
   load: 0.9
   duration: 100
  
burnram:
    load: 0.9

