version: '2'
services:
  c1:
    image: ubuntu:trusty
    command: /bin/sleep 30000

  c2:
    image: ubuntu:trusty
    command: sh -c "ping -i1 c1"
    links:
      - c1

  c3:
    image: ubuntu:trusty
    command: sh -c "ping -i1 c1"
    links:
      - c1
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
  cstar:
      image: cassandra:2.1.8
      ports:
       - ":9042:9042"
